In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("financial_dataset.csv")

In [3]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,10/21/2026 0:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,5/16/2026 0:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,6/19/2026 0:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,9/11/2027 12:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,9/22/2025 12:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,12/16/2025 12:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,1/20/2027 12:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,5/3/2027 12:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,9/13/2025 0:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,6/26/2026 0:00

In [4]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,10/21/2026 0:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,5/16/2026 0:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,6/19/2026 0:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,9/11/2027 12:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,9/22/2025 12:00

In [5]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [8]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [10]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [11]:
df["City"]=df["City"].fillna(df["City"].mode()[0])

In [13]:
df["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [14]:
df.duplicated().sum()

np.int64(40)

In [16]:
df=df.drop_duplicates()

In [18]:
df["Category"]=df["Category"].str.strip().str.title()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8628\3960893055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"]=df["Category"].str.strip().str.title()

In [20]:
df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8628\1034170163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [21]:
df["City"]=df["City"].str.strip().str.title()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8628\3137970100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.strip().str.title()

In [25]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"],errors="coarce")
df.dtypes

AssertionError: